global:
  domain: argocd.example.com

server:
  insecure: true
  service:
    type: LoadBalancer

configs:
  params:
    server.insecure: "true"

redis:
  enabled: true

controller:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  enabled: true
  replicas: 2
